import { useEffect, useState } from "react";
import { ArrowLeft, FileDown, Sheet, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getApiErrorMessage } from "../services/apiClient";
import { getCashFlowReport } from "../services/reportApi";
import type { CashFlowReport, CashFlowTransaction } from "../services/reportApi";
import { exportTableExcel, exportTablePdf } from "../utils/exportUtils";
import { formatCurrency } from "../utils/format";
import { getDefaultReportRange } from "../utils/reportUtils";

export default function CashFlowReportPage() {
  const { user } = useAuth(); const currency = user?.currency ?? "TZS";
  const initial = getDefaultReportRange("month");
  const [startDate, setStartDate] = useState(initial.startDate), [endDate, setEndDate] = useState(initial.endDate);
  const [report, setReport] = useState<CashFlowReport | null>(null), [error, setError] = useState(""), [isLoading, setIsLoading] = useState(true);
  const load = async () => { setIsLoading(true); setError(""); try { setReport(await getCashFlowReport(startDate, endDate)); } catch (err) { setError(getApiErrorMessage(err)); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const columns = [{ header: "Date", value: (row: CashFlowTransaction) => row.date }, { header: "Type", value: (row: CashFlowTransaction) => row.type.split("_").join(" ") }, { header: "Description", value: (row: CashFlowTransaction) => row.description }, { header: "Method", value: (row: CashFlowTransaction) => row.method }, { header: "Cash In", value: (row: CashFlowTransaction) => row.inflow }, { header: "Cash Out", value: (row: CashFlowTransaction) => row.outflow }];
  const pdf = () => report && exportTablePdf({ title: "Cash Flow Report", subtitle: `${startDate} to ${endDate}`, fileName: `cash-flow-${startDate}-${endDate}.pdf`, columns, rows: report.transactions, summary: [["Cash in", formatCurrency(report.summary.totalInflow, currency)], ["Cash out", formatCurrency(report.summary.totalOutflow, currency)], ["Net cash flow", formatCurrency(report.summary.netCashFlow, currency)]] });
  const excel = () => report ? exportTableExcel({ sheetName: "Cash Flow", fileName: `cash-flow-${startDate}-${endDate}.xlsx`, columns, rows: report.transactions }) : undefined;
  return <ReportShell title="Cash Flow Report" subtitle="Actual money received and paid during the selected period."><Toolbar startDate={startDate} endDate={endDate} setStartDate={setStartDate} setEndDate={setEndDate} load={load} pdf={pdf} excel={excel} disabled={!report?.transactions.length} />{error && <ErrorBox text={error} />}{isLoading ? <Loading /> : report && <><div className="mt-4 grid gap-3 sm:grid-cols-3"><Card label="Cash in" value={formatCurrency(report.summary.totalInflow, currency)} icon={TrendingUp} tone="text-leaf" /><Card label="Cash out" value={formatCurrency(report.summary.totalOutflow, currency)} icon={TrendingDown} tone="text-red-600" /><Card label="Net cash flow" value={formatCurrency(report.summary.netCashFlow, currency)} icon={WalletCards} tone={report.summary.netCashFlow >= 0 ? "text-leaf" : "text-red-600"} /></div><ReportTable rows={report.transactions} currency={currency} /></>}</ReportShell>;
}

function ReportTable({ rows, currency }: { rows: CashFlowTransaction[]; currency: string }) { return <section className="mt-4 overflow-hidden rounded-xl border border-ink/10 bg-white shadow-sm">{rows.length === 0 ? <p className="p-8 text-center text-sm font-semibold text-ink/45">No cash movements in this period.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f7faf9] text-xs uppercase text-ink/45"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Method</th><th className="px-4 py-3 text-right">Cash in</th><th className="px-4 py-3 text-right">Cash out</th></tr></thead><tbody className="divide-y divide-ink/8">{rows.map((row, index) => <tr key={`${row.date}-${row.type}-${index}`}><td className="px-4 py-3">{row.date}</td><td className="px-4 py-3 font-bold">{row.type.split("_").join(" ")}</td><td className="px-4 py-3 text-ink/60">{row.description}</td><td className="px-4 py-3 text-ink/60">{row.method}</td><td className="px-4 py-3 text-right font-bold text-leaf">{row.inflow ? formatCurrency(row.inflow, currency) : "—"}</td><td className="px-4 py-3 text-right font-bold text-red-600">{row.outflow ? formatCurrency(row.outflow, currency) : "—"}</td></tr>)}</tbody></table></div>}</section>; }

export function ReportShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="mx-auto max-w-7xl px-4 py-5 sm:px-6"><Link to="/reports" className="inline-flex items-center gap-2 text-sm font-bold text-ink/50"><ArrowLeft size={15} /> Reports</Link><h1 className="mt-4 font-display text-xl font-bold text-ink">{title}</h1><p className="mt-1 text-sm font-semibold text-ink/45">{subtitle}</p>{children}</div>; }
export function Toolbar({ startDate, endDate, setStartDate, setEndDate, load, pdf, excel, disabled }: { startDate: string; endDate: string; setStartDate: (value: string) => void; setEndDate: (value: string) => void; load: () => void; pdf: () => void; excel: () => void | Promise<void>; disabled: boolean }) { return <section className="mt-4 flex flex-col gap-3 rounded-xl border border-ink/10 bg-white p-4 shadow-sm lg:flex-row lg:items-end"><label className="text-xs font-bold text-ink/50">Start date<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="mt-1 block rounded-xl border border-ink/15 px-3 py-2 text-sm" /></label><label className="text-xs font-bold text-ink/50">End date<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="mt-1 block rounded-xl border border-ink/15 px-3 py-2 text-sm" /></label><button onClick={load} className="rounded-xl bg-leaf px-4 py-2.5 text-sm font-bold text-white">Apply</button><div className="flex gap-2 lg:ml-auto"><button disabled={disabled} onClick={pdf} className="inline-flex items-center gap-2 rounded-xl border border-ink/15 px-3 py-2 text-xs font-bold disabled:opacity-40"><FileDown size={14} /> PDF</button><button disabled={disabled} onClick={() => void excel()} className="inline-flex items-center gap-2 rounded-xl border border-ink/15 px-3 py-2 text-xs font-bold disabled:opacity-40"><Sheet size={14} /> Excel</button></div></section>; }
export function Card({ label, value, icon: Icon, tone }: { label: string; value: string; icon: typeof TrendingUp; tone: string }) { return <div className="rounded-xl border border-ink/10 bg-white p-4 shadow-sm"><Icon size={18} className={tone} /><p className="mt-3 text-xs font-bold uppercase text-ink/40">{label}</p><p className={`mt-1 text-xl font-extrabold ${tone}`}>{value}</p></div>; }
export function ErrorBox({ text }: { text: string }) { return <div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{text}</div>; }
export function Loading() { return <div className="mt-4 rounded-xl border border-ink/10 bg-white p-8 text-center text-sm font-semibold text-ink/45">Loading report...</div>; }
