import { useEffect, useState } from "react";
import { CircleDollarSign, CreditCard, ShoppingCart } from "lucide-react";
import { useAuth } from "../auth/AuthContext";
import { getApiErrorMessage } from "../services/apiClient";
import { getPurchaseReport } from "../services/reportApi";
import type { PurchaseReport, PurchaseReportRow } from "../services/reportApi";
import { exportTableExcel, exportTablePdf } from "../utils/exportUtils";
import { formatCurrency } from "../utils/format";
import { getDefaultReportRange } from "../utils/reportUtils";
import { Card, ErrorBox, Loading, ReportShell, Toolbar } from "./CashFlowReportPage";

export default function PurchaseReportPage() {
  const { user } = useAuth(); const currency = user?.currency ?? "TZS"; const initial = getDefaultReportRange("month");
  const [startDate, setStartDate] = useState(initial.startDate), [endDate, setEndDate] = useState(initial.endDate), [report, setReport] = useState<PurchaseReport | null>(null), [error, setError] = useState(""), [isLoading, setIsLoading] = useState(true);
  const load = async () => { setIsLoading(true); setError(""); try { setReport(await getPurchaseReport(startDate, endDate)); } catch (err) { setError(getApiErrorMessage(err)); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const columns = [{ header: "Date", value: (row: PurchaseReportRow) => row.createdAt }, { header: "Order", value: (row: PurchaseReportRow) => row.orderNumber }, { header: "Supplier", value: (row: PurchaseReportRow) => row.supplier ?? "No supplier" }, { header: "Status", value: (row: PurchaseReportRow) => row.status }, { header: "Items", value: (row: PurchaseReportRow) => row.items }, { header: "Total", value: (row: PurchaseReportRow) => row.totalAmount }, { header: "Paid", value: (row: PurchaseReportRow) => row.paidAmount }, { header: "Outstanding", value: (row: PurchaseReportRow) => row.outstanding }];
  const pdf = () => report && exportTablePdf({ title: "Purchase Report", subtitle: `${startDate} to ${endDate}`, fileName: `purchase-report-${startDate}-${endDate}.pdf`, columns, rows: report.purchases, summary: [["Purchases", formatCurrency(report.summary.totalPurchases, currency)], ["Paid", formatCurrency(report.summary.paid, currency)], ["Outstanding", formatCurrency(report.summary.outstanding, currency)]] });
  const excel = () => report ? exportTableExcel({ sheetName: "Purchases", fileName: `purchase-report-${startDate}-${endDate}.xlsx`, columns, rows: report.purchases }) : undefined;
  return <ReportShell title="Purchase Report" subtitle="Purchase orders, supplier totals, payments, and outstanding balances."><Toolbar startDate={startDate} endDate={endDate} setStartDate={setStartDate} setEndDate={setEndDate} load={load} pdf={pdf} excel={excel} disabled={!report?.purchases.length} />{error && <ErrorBox text={error} />}{isLoading ? <Loading /> : report && <><div className="mt-4 grid gap-3 sm:grid-cols-4"><Card label="Orders" value={String(report.summary.orders)} icon={ShoppingCart} tone="text-ink" /><Card label="Purchases" value={formatCurrency(report.summary.totalPurchases, currency)} icon={CircleDollarSign} tone="text-ink" /><Card label="Paid" value={formatCurrency(report.summary.paid, currency)} icon={CreditCard} tone="text-leaf" /><Card label="Outstanding" value={formatCurrency(report.summary.outstanding, currency)} icon={CreditCard} tone="text-red-600" /></div><section className="mt-4 overflow-hidden rounded-xl border border-ink/10 bg-white shadow-sm">{report.purchases.length === 0 ? <p className="p-8 text-center text-sm font-semibold text-ink/45">No purchases in this period.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#f7faf9] text-xs uppercase text-ink/45"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Order</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Paid</th><th className="px-4 py-3 text-right">Outstanding</th></tr></thead><tbody className="divide-y divide-ink/8">{report.purchases.map((row) => <tr key={row.id}><td className="px-4 py-3">{row.createdAt}</td><td className="px-4 py-3 font-bold">{row.orderNumber}</td><td className="px-4 py-3">{row.supplier ?? "—"}</td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3 text-right font-bold">{formatCurrency(row.totalAmount, currency)}</td><td className="px-4 py-3 text-right text-leaf">{formatCurrency(row.paidAmount, currency)}</td><td className="px-4 py-3 text-right font-bold text-red-600">{formatCurrency(row.outstanding, currency)}</td></tr>)}</tbody></table></div>}</section></>}</ReportShell>;
}
