import { useEffect, useState } from "react";
import { ArrowLeft, Printer } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getApiErrorMessage } from "../services/apiClient";
import { getSaleById } from "../services/saleService";
import type { Sale } from "../types/sale";
import { formatCurrency } from "../utils/format";

export default function SaleReceiptPage() {
  const { id = "" } = useParams();
  const { user } = useAuth();
  const [sale, setSale] = useState<Sale | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getSaleById(id)
      .then((result) => setSale(result ?? null))
      .catch((err) => setError(getApiErrorMessage(err)));
  }, [id]);

  if (error) return <div className="mx-auto max-w-3xl p-6 text-sm font-semibold text-red-600">{error}</div>;
  if (!sale) return <div className="mx-auto max-w-3xl p-6 text-sm font-semibold text-ink/45">Loading document...</div>;

  const netAmount = sale.totalAmount - sale.discount - sale.promotionDiscount + sale.taxAmount;
  const documentLabel = sale.balanceDue > 0 ? "INVOICE" : "RECEIPT";

  return (
    <div className="mx-auto max-w-3xl px-4 py-5 sm:px-6">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <Link to="/sales" className="inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft size={16} /> Back to sales</Link>
        <button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-bold text-white"><Printer size={16} /> Print / Save PDF</button>
      </div>

      <article className="rounded-2xl border border-ink/10 bg-white p-6 shadow-sm print:border-0 print:shadow-none sm:p-9">
        <header className="flex items-start justify-between gap-6 border-b border-ink/10 pb-6">
          <div><p className="text-2xl font-black text-leaf">{user?.businessName ?? "BizTrack Business"}</p><p className="mt-1 text-sm text-ink/50">{user?.country ?? ""}</p></div>
          <div className="text-right"><h1 className="text-2xl font-black tracking-widest text-ink">{documentLabel}</h1><p className="mt-1 font-mono text-sm font-bold text-ink/60">{sale.receiptNumber ?? sale.id.slice(0, 8)}</p></div>
        </header>

        <section className="grid gap-5 border-b border-ink/10 py-6 sm:grid-cols-2">
          <div><p className="text-xs font-bold uppercase tracking-wide text-ink/40">Customer</p><p className="mt-1 font-bold text-ink">{sale.customerName || "Walk-in customer"}</p></div>
          <div className="sm:text-right"><p className="text-xs font-bold uppercase tracking-wide text-ink/40">Sale date</p><p className="mt-1 font-bold text-ink">{new Date(`${sale.saleDate}T00:00:00`).toLocaleDateString()}</p>{sale.paymentDueDate && sale.balanceDue > 0 && <p className="mt-1 text-xs font-semibold text-red-600">Due {new Date(`${sale.paymentDueDate}T00:00:00`).toLocaleDateString()}</p>}</div>
        </section>

        <table className="mt-6 w-full text-left text-sm">
          <thead className="bg-[#f7faf9] text-xs uppercase text-ink/45"><tr><th className="px-3 py-2.5">Item</th><th className="px-3 py-2.5 text-right">Qty</th><th className="px-3 py-2.5 text-right">Price</th><th className="px-3 py-2.5 text-right">Amount</th></tr></thead>
          <tbody><tr className="border-b border-ink/10"><td className="px-3 py-4 font-bold">{sale.productName}</td><td className="px-3 py-4 text-right">{sale.quantity}</td><td className="px-3 py-4 text-right">{formatCurrency(sale.unitPrice, user?.currency)}</td><td className="px-3 py-4 text-right font-bold">{formatCurrency(sale.totalAmount, user?.currency)}</td></tr></tbody>
        </table>

        <section className="ml-auto mt-6 max-w-sm space-y-2 text-sm">
          <Line label="Subtotal" value={formatCurrency(sale.totalAmount, user?.currency)} />
          <Line label="Discount" value={`- ${formatCurrency(sale.discount, user?.currency)}`} />
          {sale.promotionDiscount > 0 && <Line label="Promotion" value={`- ${formatCurrency(sale.promotionDiscount, user?.currency)}`} />}
          <Line label={`Tax / VAT (${sale.taxRate}%)`} value={formatCurrency(sale.taxAmount, user?.currency)} />
          <Line label="Total" value={formatCurrency(netAmount, user?.currency)} strong />
          <Line label="Paid" value={formatCurrency(sale.paidAmount, user?.currency)} />
          <Line label="Balance due" value={formatCurrency(sale.balanceDue, user?.currency)} strong alert={sale.balanceDue > 0} />
        </section>

        <footer className="mt-10 border-t border-ink/10 pt-5 text-center text-xs font-semibold text-ink/45">Thank you for your business. Generated by BizTrack.</footer>
      </article>
    </div>
  );
}

function Line({ label, value, strong = false, alert = false }: { label: string; value: string; strong?: boolean; alert?: boolean }) {
  return <div className={`flex justify-between gap-4 ${strong ? "border-t border-ink/10 pt-2 text-base font-extrabold" : "font-semibold"}`}><span className="text-ink/55">{label}</span><span className={alert ? "text-red-600" : "text-ink"}>{value}</span></div>;
}
