<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\Business;
use App\Models\BusinessMembership;
use App\Models\User;
use App\Services\AuditService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
class StaffController extends Controller
{
    public const PERMISSIONS=['dashboard.view','sales.view','sales.create','sales.edit','sales.delete','expenses.view','expenses.manage','products.view','products.manage','inventory.view','inventory.manage','purchases.view','purchases.manage','customers.view','customers.manage','reports.view','settings.manage','branches.manage','staff.manage','promotions.manage'];
    private function business():?Business{return Business::forUser(auth()->user());}
    public function index():JsonResponse{$business=$this->business();$members=$business?->memberships()->with(['user','branch'])->get()??collect();return response()->json(['success'=>true,'data'=>['staff'=>$members->map(fn($m)=>$this->format($m)),'permissions'=>self::PERMISSIONS]]);}
    public function store(Request $request):JsonResponse{$business=$this->business();if(!$business)return response()->json(['success'=>false,'error'=>'Business not found'],404);$data=$request->validate(['name'=>'required|string|max:255','email'=>'required|email|max:255','phone'=>'nullable|string|max:50','password'=>'nullable|string|min:8','role'=>'required|in:MANAGER,CASHIER,INVENTORY,ACCOUNTANT,CUSTOM','branchId'=>'nullable|uuid','permissions'=>'nullable|array','permissions.*'=>'in:'.implode(',',self::PERMISSIONS)]);if(!empty($data['branchId'])&&!$business->branches()->where('id',$data['branchId'])->exists())return response()->json(['success'=>false,'error'=>'Branch not found for this business'],422);$user=User::where('email',$data['email'])->first();if(!$user){if(empty($data['password']))return response()->json(['success'=>false,'error'=>'A temporary password is required for a new staff account'],422);$user=User::create(['name'=>$data['name'],'email'=>$data['email'],'phone'=>$data['phone']??null,'password_hash'=>Hash::make($data['password']),'role'=>'USER','status'=>'ACTIVE','email_verified_at'=>now()]);}if(BusinessMembership::where('business_id',$business->id)->where('user_id',$user->id)->exists())return response()->json(['success'=>false,'error'=>'This user is already a member of the business'],409);$membership=BusinessMembership::create(['business_id'=>$business->id,'user_id'=>$user->id,'branch_id'=>$data['branchId']??null,'role'=>$data['role'],'permissions'=>$this->permissions($data['role'],$data['permissions']??[]),'status'=>'ACTIVE']);$this->audit('STAFF_ADDED',$membership->id);return response()->json(['success'=>true,'data'=>$this->format($membership->load(['user','branch']))],201);}
    public function update(Request $request,string $id):JsonResponse{$business=$this->business();$membership=$business?->memberships()->where('role','<>','OWNER')->find($id);if(!$membership)return response()->json(['success'=>false,'error'=>'Staff membership not found'],404);$data=$request->validate(['role'=>'sometimes|in:MANAGER,CASHIER,INVENTORY,ACCOUNTANT,CUSTOM','branchId'=>'nullable|uuid','permissions'=>'nullable|array','permissions.*'=>'in:'.implode(',',self::PERMISSIONS),'status'=>'sometimes|in:ACTIVE,INACTIVE']);$role=$data['role']??$membership->role;$membership->update(['role'=>$role,'branch_id'=>array_key_exists('branchId',$data)?$data['branchId']:$membership->branch_id,'permissions'=>array_key_exists('permissions',$data)?$this->permissions($role,$data['permissions']):$membership->permissions,'status'=>$data['status']??$membership->status]);$this->audit('STAFF_UPDATED',$id);return response()->json(['success'=>true,'data'=>$this->format($membership->fresh()->load(['user','branch']))]);}
    public function destroy(string $id):JsonResponse{$business=$this->business();$membership=$business?->memberships()->where('role','<>','OWNER')->find($id);if(!$membership)return response()->json(['success'=>false,'error'=>'Staff membership not found'],404);$membership->delete();$this->audit('STAFF_REMOVED',$id);return response()->json(['success'=>true,'data'=>['message'=>'Staff removed']]);}
    private function permissions(string $role,array $custom):array{return match($role){'MANAGER'=>array_values(array_diff(self::PERMISSIONS,['staff.manage'])),'CASHIER'=>['dashboard.view','sales.view','sales.create','products.view','customers.view','customers.manage'],'INVENTORY'=>['dashboard.view','products.view','products.manage','inventory.view','inventory.manage','purchases.view','purchases.manage'],'ACCOUNTANT'=>['dashboard.view','sales.view','expenses.view','expenses.manage','products.view','purchases.view','reports.view','customers.view'],default=>array_values(array_unique($custom))};}
    private function format(BusinessMembership $m):array{return['id'=>$m->id,'user'=>['id'=>$m->user->id,'name'=>$m->user->name,'email'=>$m->user->email,'phone'=>$m->user->phone],'role'=>$m->role,'permissions'=>$m->permissions??[],'status'=>$m->status,'branch'=>$m->branch?['id'=>$m->branch->id,'name'=>$m->branch->name]:null,'createdAt'=>$m->created_at];}
    private function audit(string $action,string $id):void{AuditService::log(['actor_id'=>auth()->id(),'action'=>$action,'target_type'=>'BusinessMembership','target_id'=>$id]);}
}
